// Code generated by "stringer -type=ActionType"; DO NOT EDIT.

package phase

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChooseCard-0]
	_ = x[ReduceResources-1]
	_ = x[UseResources-2]
	_ = x[SkipUseResources-3]
}

const _ActionType_name = "ChooseCardReduceResourcesUseResourcesSkipUseResources"

var _ActionType_index = [...]uint8{0, 10, 25, 37, 53}

func (i ActionType) String() string {
	if i < 0 || i >= ActionType(len(_ActionType_index)-1) {
		return "ActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[i]:_ActionType_index[i+1]]
}
