// Code generated by "stringer -type=CardOrientation"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VictoryPoints-0]
	_ = x[Upgrade-1]
	_ = x[Trade-2]
	_ = x[Generate-3]
	_ = x[Payment-4]
}

const _CardOrientation_name = "VictoryPointsUpgradeTradeGeneratePayment"

var _CardOrientation_index = [...]uint8{0, 13, 20, 25, 33, 40}

func (i CardOrientation) String() string {
	if i < 0 || i >= CardOrientation(len(_CardOrientation_index)-1) {
		return "CardOrientation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardOrientation_name[_CardOrientation_index[i]:_CardOrientation_index[i+1]]
}
